
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqqilcfxalztcizvchsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcWlsY2Z4YWx6dGNpenZjaHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjg0MjgsImV4cCI6MjA1NjgwNDQyOH0.UGLBhCWpnPqwhHbPEpjAODUjmDNmB02oCluTFYEThkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define custom types for the zohour table to help with TypeScript
export type PatientData = {
  id?: string;
  "Card No"?: number | null;
  "Name"?: string | null;
  "Agenda"?: string | null;
  "Organization"?: string | null;
  "Page No"?: string | null;
  "Phone.No"?: string | null;
  "Notes"?: string | null;
  created_at?: string | null;
};
